# Site
repository: richteague.github.io
favicon: images/favicon.ico

# Personal info
name: Richard Teague
title: Astronomer at the University of Michigan
email: rteague@umich.edu
website: https://richteague.github.io

# Social links
github_username:  richteague

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  I'm an postdoctoral fellow at the University of Michigan working in the group of Prof. Ted Bergin on understanding planet formation. I have previously studied at the Unversity of Edinburgh for my MPhys in Astrophysics, then at MPIA in Heidelberg where I obtained my PhD in Astronomy, supervised by Prof. Thomas Henning and Dr. Dmitry Semenov.

  I work primarily with radio observations of simple molecules in protoplanetary disks, the sites of planet formation. I am mostly interested in the dynamics of the gas as this provides a unique way of searching for embedded planets. I also work extensively on inferring the physical and chemical structures of these disks in order to better interpret the dynamical information we extract. My [ADS Library](https://ui.adsabs.harvard.edu/#/public-libraries/uxd2UZZ5QSGSqcI7i3llMQ) contains a list of all my publications.

# More Section
more_title: Diversity, Equity and Inclusion
more_content: | # this will include new lines to allow paragraphs

  A diverse and inclusive astronomy is important for everyone. I am working as part of the [UMich Astronomy Diversity, Equity and Inclusion committe](https://sites.google.com/umich.edu/astro-dei) to help implement iniatives aimed at creating a more inclusive department. As part of this, I run the monthly DEI journal club, [Equitea](https://sites.google.com/umich.edu/astro-dei/equi-tea) where we discuss recent papers, talks or issues relating to DEI.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
