# Site
repository: richteague.github.io
# favicon: images/favicon.ico

# Personal info
name: Richard Teague
title: SMA Fellow at the Center for Astrophysics
email: richard.d.teague@cfa.harvard.edu
website: richteague.github.io

# Social links
github_username: richteague

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  I'm an SMA Fellow at the Harvard-Smithsonian Center for Astrophysics where I work on understanding the planet formation process and its environment, the protoplanetary disk. Previously I was a postdoctoral researcher at the University of Michigan working in the group of Prof. Ted Bergin. Before that, I studied at the Unversity of Edinburgh for my MPhys in Astrophysics, then at MPIA in Heidelberg where I obtained my PhD in Astronomy, supervised by Prof. Thomas Henning and Dr. Dmitry Semenov.

  I work primarily with radio observations of simple molecules in protoplanetary disks. I am mostly interested in the dynamics of the gas as this provides a unique way of searching for embedded planets and understanding the physical processes which are sculting the structures we see in the dust. I also work extensively on inferring the physical and chemical structures of these disks in order to better interpret the dynamical information we extract.

  My [ADS Library](https://ui.adsabs.harvard.edu/#/public-libraries/uxd2UZZ5QSGSqcI7i3llMQ) contains a list of all my publications. You can also check out my [CV](https://www.google.com).

# More Section
more_title: Press Releases
more_content: | # this will include new lines to allow paragraphs

  Some of the work I have lead and been involved in has been featured in various news outlets.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
