# Site
repository: richteague.github.io
favicon: images/favicon.ico

# Personal info
name: Richard Teague
title: Astronomer at the University of Michigan
email: rteague@umich.edu
website: www.richteague.github.io

# Social links
github_username:  richteague

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  I'm an astronomer at the University of Michigan working on understanding planet formation. I work primarily with radio telescopes looking at emission from simple molecules which tell us all about the formation process.

  Testing this...


# Projects Section
projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
